cabal-version:      3.0

name:               Compiler

version:            0.1.0.0
license:            GPL-3.0-only
license-file:       LICENSE
build-type:         Simple

extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

flag debug
     description: "Enable debug output"
     default: False
     manual: True

library
    import:         warnings
    hs-source-dirs: src
    exposed-modules:
        Common.SourcePosition
        Lexer.Monad
        Lexer.Token
        Lexer.Rules
        Parser.Monad
        Parser.Ast
        Parser.Rules
        Intermediate.Serialization
    build-depends:
        base
      , mtl
      , containers
    default-language: GHC2021
    if flag(debug)
        cpp-options: -DDEBUG

executable Compiler
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base
      , Compiler
    hs-source-dirs:   app
    default-language: GHC2021
    if flag(debug)
        cpp-options: -DDEBUG


test-suite tests
    type:             exitcode-stdio-1.0
    main-is:          Spec.hs
    other-modules:
        LexerSpec
        ParserSpec
        IntermediateSpec
    hs-source-dirs:   test
    build-depends:
        base
      , Compiler
      , hspec
    default-language: GHC2021
